version: 0.0
os: linux
files:
  - source: /home.php
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_webserver.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root




